name: Test commit and push
on:
  push:
    branches: [main]
jobs:
  test-commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: bar
      - run: |
          find . -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +
          echo "$RANDOM" > README.txt
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: bar
