name: deploy inside a subdirectory on pr
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "14"
  #     - run: npm install -g bats
  #     - run: bats -v
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "${PR_NUMBER}" >> out
          echo "$(git rev-parse --abbrev-ref HEAD)" >> out
          echo "" >> out
          echo "$(git log -n 1)" >> out
      - uses: actions/upload-artifact@v3
        with:
          name: out
          path: out
      # - uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
