name: deploy inside a subdirectory on pr
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # ref: ${{ github.event.pull_request.head.ref }}
      - env:
          SUBDIR: __PR${{ github.event.number }}__
        run: |
          mv public "$SUBDIR"
          mkdir public
          mv "$SUBDIR" public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true
