name: PR previews
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v4
        with:
          path: main
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v4
        with:
          repository: rjooske/play-with-github2
          path: play-with-github2
      - env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          which tree && tree
          ls -lahR
