name: PR previews
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: play-with-github
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v4
        with:
          repository: rjooske/play-with-github2
          path: play-with-github2
      - env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          rm -rf "play-with-github2/${PR_NUMBER}"
          mv play-with-github/public play-with-github2/${PR_NUMBER}
          cd play-with-github2
          git add .
          git commit -m "PR#${PR_NUMBER}"
          git push
