name: Create PR previews
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: pr
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages
      - env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir gh-pages/__pr_previews__
          rm -rf "gh-pages/__pr_previews__/${PR_NUMBER}"
          mv pr/public "gh-pages/__pr_previews__/${PR_NUMBER}"
          cd gh-pages
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          message: preview PR#${{ github.event.number }}
