name: PR previews
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p publish_dir/__pr_previews__
          mv public publish_dir/__pr_previews__/"$PR_NUMBER"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish_dir
          keep_files: true
