name: PR previews
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ github.secrets.PAT }}
        run: |
          git config --global user.email "rjooske@gmail.com"
          git config --global user.name "Ryosuke Takahashi"
          git clone --depth 1 https://github.com/rjooske/play-with-github2
          cd play-with-github2
          mv ../public "${PR_NUMBER}"
          git add .
          git commit -m "PR#${PR_NUMBER} $(git rev-parse HEAD)"
          git push
